{% set name = "lume-genesis" %}
{% set version = "1.3.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a277fd1ded6bfd46adefb8f283fe281e49b95cbb3427e4dc8007b57c78d89a72

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - eval-type-backport
    - genesis2
    - genesis4 >=4.6.7
    - h5py
    - jinja2
    - lark
    - lume-base
    - matplotlib-base
    - numpy
    - openpmd-beamphysics
    - prettytable
    - psutil
    - pydantic >=2.7
    - pydantic-settings
    - scipy
    - typing-extensions

test:
  imports:
    - genesis
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - ffmpeg
  source_files:
    - docs
    - genesis
    - pyproject.toml
  commands:
    # Avoid a couple tests which require a lot of memory (15.3GiB)
    - pytest -v -k 'not particles and not profile_array'

about:
  home: https://github.com/slaclab/lume-genesis
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Genesis tools for use in LUME
  description: |
    Genesis tools for use in LUME.

extra:
  recipe-maintainers:
    - balticfish
    - ChristopherMayes
    - ken-lauer
