{% set name = "lume-genesis" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 232077c10ce589995522c990b664897e933236c0581e21b75577b9252ba69ef7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bokeh
    - h5py
    - matplotlib-base
    - numpy
    - scipy
    - genesis2

test:
  imports:
    - genesis

about:
  home: https://github.com/slaclab/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Genesis tools for use in LUME
  description: |
    Genesis tools for use in LUME.

extra:
  recipe-maintainers:
    - balticfish
    - ChristopherMayes
