{% set name = "lume-genesis" %}
{% set version = "1.4.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 136ce0e0d320fbe374c9d66df99a1bf63817b50f69cc738943a3a52db87c8c53

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - genesis2
    - genesis4 >=4.6.12
    - h5py
    - jinja2
    - lark
    - lume-base
    - matplotlib-base
    - numpy
    - openpmd-beamphysics >=0.14.1
    - ormsgpack
    - prettytable
    - psutil
    - pydantic >=2.12.0
    - pydantic-settings
    - scipy
    - typing-extensions

test:
  imports:
    - genesis
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - ffmpeg
  source_files:
    - docs
    - genesis
    - pyproject.toml
  commands:
    # Avoid a couple tests which require a lot of memory (15.3GiB)
    - pytest -v -k 'not particles and not profile_array'

about:
  home: https://github.com/slaclab/lume-genesis
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Genesis tools for use in LUME
  description: |
    Genesis tools for use in LUME.

extra:
  recipe-maintainers:
    - balticfish
    - ChristopherMayes
    - ken-lauer
